"""empty message

Revision ID: 49e83777c969
Revises: 0ed2bad3d187
Create Date: 2025-09-24 21:01:19.547902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e83777c969'
down_revision = '0ed2bad3d187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task', sa.Text(), nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('job')
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('job', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=False))
        batch_op.drop_column('task')

    # ### end Alembic commands ###
