"""empty message

Revision ID: 86b545d3c49d
Revises: 49e83777c969
Create Date: 2025-09-24 21:02:10.369631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b545d3c49d'
down_revision = '49e83777c969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.drop_table('people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('pid', sa.INTEGER(), nullable=False),
    sa.Column('task', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    op.drop_table('tasks')
    # ### end Alembic commands ###
